AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
    zoomit-be

    Nested stack S3 functions

Globals:
    Function:
        Timeout: 30
        Tracing: Active
        LoggingConfig:
            LogFormat: JSON
        Environment:
            Variables:
                POSTGRES_USER: !Ref POSTGRES_USER
                POSTGRES_PASSWORD: !Ref POSTGRES_PASSWORD
                POSTGRES_PORT: !Ref POSTGRES_PORT
                POSTGRES_HOST: !Ref POSTGRES_HOST
                POSTGRES_DB: !Ref POSTGRES_DB
                STAGE_NAME: !Ref STAGE_NAME
                JWT_REFRESH_SECRET: !Ref JWT_REFRESH_SECRET
                JWT_ACCESS_SECRET: !Ref JWT_ACCESS_SECRET

Parameters:
    POSTGRES_USER:
        Type: String
        Description: DB Username
    POSTGRES_PASSWORD:
        Type: String
        Description: DB Password
    POSTGRES_PORT:
        Type: String
        Description: DB Port
    POSTGRES_HOST:
        Type: String
        Description: DB Host
    POSTGRES_DB:
        Type: String
        Description: DB Name
    STAGE_NAME:
        Type: String
        Description: Stage name
    JWT_REFRESH_SECRET:
        Type: String
        Description: JWT refresh token secret
    JWT_ACCESS_SECRET:
        Type: String
        Description: JWT access token secret

Resources:
    GetNetworkFunction:
        Type: AWS::Serverless::Function
        Properties:
            CodeUri: ../
            Handler: index.handler
            Runtime: nodejs20.x
            Architectures:
                - arm64
            Events:
                HelloWorld:
                    Type: Api
                    Properties:
                        Path: /network
                        Method: get
        Metadata:
            BuildMethod: esbuild
            BuildProperties:
                Minify: true
                Target: es2020
                Sourcemap: true
                EntryPoints:
                    - functions/s3.ts

Outputs:
