AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
    zoomit-be

    Nested stack S3 functions

Globals:
    Function:
        Timeout: 30
        Tracing: Active
        LoggingConfig:
            LogFormat: JSON
        Environment:
            Variables:
                POSTGRES_USER: !Ref DBUser
                POSTGRES_PASSWORD: !Ref DBPassword
                POSTGRES_PORT: !Ref DBPort
                POSTGRES_HOST: !Ref DBHost
                POSTGRES_DB: !Ref DBName
                STAGE_NAME: !Ref Stage
                JWT_REFRESH_SECRET: !Ref JwtRefreshSecret
                JWT_ACCESS_SECRET: !Ref JwtAccessSecret

Parameters:
    DBUser:
        Type: String
        Description: DB Username
    DBPassword:
        Type: String
        Description: DB Password
    DBPort:
        Type: String
        Description: DB Port
    DBHost:
        Type: String
        Description: DB Host
    DBName:
        Type: String
        Description: DB Name
    Stage:
        Type: String
        Description: Stage name
    JwtRefreshSecret:
        Type: String
        Description: JWT refresh token secret
    JwtAccessSecret:
        Type: String
        Description: JWT access token secret

Resources:
    GetNetworkFunction:
        Type: AWS::Serverless::Function
        Properties:
            CodeUri: ../
            Handler: index.handler
            Runtime: nodejs20.x
            Architectures:
                - arm64
            Events:
                HelloWorld:
                    Type: Api
                    Properties:
                        Path: /network
                        Method: get
        Metadata:
            BuildMethod: esbuild
            BuildProperties:
                Minify: true
                Target: es2020
                Sourcemap: true
                EntryPoints:
                    - functions/s3.ts

Outputs:
