AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
    zoomit-be

    Nested stack functions

Globals:
    Function:
        Timeout: 30
        Tracing: Active
        LoggingConfig:
            LogFormat: JSON
        Environment:
            Variables:
                POSTGRES_USER: !Ref DBUser
                POSTGRES_PASSWORD: !Ref DBPassword
                POSTGRES_PORT: !Ref DBPort
                POSTGRES_HOST: !Ref DBHost
                POSTGRES_DB: !Ref DBName
                STAGE_NAME: !Ref Stage
                JWT_REFRESH_SECRET: !Ref JwtRefreshSecret
                JWT_ACCESS_SECRET: !Ref JwtAccessSecret
Parameters:
    DBUser:
        Type: String
        Description: DB Username
    DBPassword:
        Type: String
        Description: DB Password
    DBPort:
        Type: String
        Description: DB Port
    DBHost:
        Type: String
        Description: DB Host
    DBName:
        Type: String
        Description: DB Name
    Stage:
        Type: String
        Description: Stage name
    JwtRefreshSecret:
        Type: String
        Description: JWT refresh token secret
    JwtAccessSecret:
        Type: String
        Description: JWT access token secret

Resources:
    AuthLoginFunction:
        Type: AWS::Serverless::Function
        Properties:
            CodeUri: ../
            Handler: auth.loginHandler
            Runtime: nodejs20.x
            Architectures:
                - arm64
            Events:
                HelloWorld:
                    Type: Api
                    Properties:
                        Path: /auth/login
                        Method: post
                        RestApiId:
                            Ref: 9lvt6cq0dd
        Metadata:
            BuildMethod: esbuild
            BuildProperties:
                Minify: true
                Target: es2020
                Sourcemap: true
                EntryPoints:
                    - functions/auth.ts
    AuthSignupFunction:
        Type: AWS::Serverless::Function
        Properties:
            CodeUri: ../
            Handler: auth.signupHandler
            Runtime: nodejs20.x
            Architectures:
                - arm64
            Events:
                HelloWorld:
                    Type: Api
                    Properties:
                        Path: /auth/signup
                        Method: post
                        RestApiId:
                            Ref: 9lvt6cq0dd
        Metadata:
            BuildMethod: esbuild
            BuildProperties:
                Minify: true
                Target: es2020
                Sourcemap: true
                EntryPoints:
                    - functions/auth.ts
    AuthRefreshTokenFunction:
        Type: AWS::Serverless::Function
        Properties:
            CodeUri: ../
            Handler: auth.refreshTokenHandler
            Runtime: nodejs20.x
            Architectures:
                - arm64
            Events:
                HelloWorld:
                    Type: Api
                    Properties:
                        Path: /auth/refresh-token
                        Method: post
                        RestApiId:
                            Ref: 9lvt6cq0dd
        Metadata:
            BuildMethod: esbuild
            BuildProperties:
                Minify: true
                Target: es2020
                Sourcemap: true
                EntryPoints:
                    - functions/auth.ts
    AuthNicknameFunction:
        Type: AWS::Serverless::Function
        Properties:
            CodeUri: ../
            Handler: auth.nicknameHandler
            Runtime: nodejs20.x
            Architectures:
                - arm64
            Events:
                HelloWorld:
                    Type: Api
                    Properties:
                        Path: /auth/nickname
                        Method: post
                        RestApiId:
                            Ref: 9lvt6cq0dd
        Metadata:
            BuildMethod: esbuild
            BuildProperties:
                Minify: true
                Target: es2020
                Sourcemap: true
                EntryPoints:
                    - functions/auth.ts
Outputs:
    ZoomitApi:
        Description: 'API Gateway endpoint URL for Prod stage for Hello World function'
        Value: !Sub 'https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/${Stage}/'
    AuthLoginFunctionArn:
        Description: 'ARN of the AuthLogin Lambda function'
        Value: !GetAtt AuthLoginFunction.Arn

    AuthSignupFunctionArn:
        Description: 'ARN of the AuthSignup Lambda function'
        Value: !GetAtt AuthSignupFunction.Arn

    AuthRefreshTokenFunctionArn:
        Description: 'ARN of the AuthRefreshToken Lambda function'
        Value: !GetAtt AuthRefreshTokenFunction.Arn

    AuthNicknameFunctionArn:
        Description: 'ARN of the AuthNickname Lambda function'
        Value: !GetAtt AuthNicknameFunction.Arn
