version: '3.8'
services:
  postgres:
    container_name: container-pg
    image: postgres
    hostname: localhost
    ports:
      - '5435:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: zoomitdb
    volumes:
      - pg:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  pg:
