# More information about the configuration file can be found here:
# https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/serverless-sam-cli-config.html
version = 0.1

[default]
[default.global.parameters]
stack_name = "zoomit-be"

[default.build.parameters]
cached = false
parallel = true

[default.validate.parameters]
lint = true

[default.deploy.parameters]
capabilities = "CAPABILITY_IAM"
confirm_changeset = true
resolve_s3 = true
parameter_overrides = "DBUser=\"postgres\" DBPassword=\"postgres\" DBName=\"zoomitdb\" DBPort=\"5432\" DBHost=\"http://localhost:3000\" Stage=\"dev\""

[default.package.parameters]
resolve_s3 = true

[default.sync.parameters]
watch = true

[default.local_start_api.parameters]
warm_containers = "EAGER"
parameter_overrides = "DBUser=\"postgres\" DBPassword=\"postgres\" DBName=\"zoomitdb\" DBPort=\"5432\" DBHost=\"http://localhost:3000\" Stage=\"dev\""

[default.local_start_lambda.parameters]
warm_containers = "EAGER"
parameter_overrides = "DBUser=\"postgres\" DBPassword=\"postgres\" DBName=\"zoomitdb\" DBPort=\"5432\" DBHost=\"http://localhost:3000\" Stage=\"dev\""