AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  zoomit-be

  Sample SAM Template for zoomit-be

Parameters:
  DBUser:
    Type: String
    Description: DB Username
  DBPassword:
    Type: String
    Description: DB Password
  DBPort:
    Type: String
    Description: DB Port
  DBHost:
    Type: String
    Description: DB Host
  DBName:
    Type: String
    Description: DB Name
  Stage:
    Type: String
    Description: Stage name
  JwtRefreshSecret:
    Type: String
    Description: JWT refresh token secret
  JwtAccessSecret:
    Type: String
    Description: JWT access token secret
Resources:
  GetNetworkFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./src
      Handler: index.handler
      Runtime: nodejs20.x
      Architectures:
        - arm64
      Events:
        HelloWorld:
          Type: Api
          Properties:
            Path: /network
            Method: get
    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        Minify: true
        Target: es2020
        Sourcemap: true
        EntryPoints:
          - functions/index.ts
  FunctionsNested:
    Type: AWS::Serverless::Application
    Properties:
      Location: ./src/resources/userFunctions.yaml
      Parameters:
        DBHost: !Ref DBHost
        DBPort: !Ref DBPort
        DBUser: !Ref DBUser
        DBPassword: !Ref DBPassword
        DBName: !Ref DBName
        Stage: !Ref Stage
        JwtRefreshSecret: !Ref JwtRefreshSecret
        JwtAccessSecret: !Ref JwtAccessSecret

  ApplicationResourceGroup:
    Type: AWS::ResourceGroups::Group
    Properties:
      Name:
        Fn::Sub: ApplicationInsights-SAM-${AWS::StackName}
      ResourceQuery:
        Type: CLOUDFORMATION_STACK_1_0
  ApplicationInsightsMonitoring:
    Type: AWS::ApplicationInsights::Application
    Properties:
      ResourceGroupName:
        Ref: ApplicationResourceGroup
      AutoConfigurationEnabled: 'true'
Outputs:
  ZoomitApi:
    Description: 'API Gateway endpoint URL for Prod stage for Hello World function'
    Value: !Sub 'https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/${Stage}/'
